### ISSUE TITLE
GraphQL error: Field "small_image" of type "ProductImage" must have a sub selection.

### ISSUE THREAD

**Issue by skonudula** [magento-research/magento2-upward-connector#15]
Hello, 
I have executed all the steps which you provided in the "how to install" section, now am able to see the Venia storefront but there is an error while data fetching.

Below is the error am seeing on the application, can you help me on how can i fix this issue?

Data Fetch Error:
GraphQL error: Field "small_image" of type "ProductImage" must have a sub selection.

**Comment by johan-lindahl** [comment]
The GraphQL interface has been updated so you need to pass a { url } selection. But I guess you will have more issues. Your problem is that your PWA store front code and your backend Magento got a version mismatch. Either downgrade your server or upgrade your PWA.

**Comment by zetlen** [comment]
Closing because this appears unrelated to this code.
