### ISSUE TITLE
magento 2.4.3 installation issue

### ISSUE THREAD

**Issue by mohdaali27** [magento-research/magento2-upward-connector#39]
I am installing the extension using composer -  **composer require magento/module-upward-connector** but getting the below error 
![image](https://user-images.githubusercontent.com/80909837/135432390-c5832087-d79e-458d-a97a-376bea4d91d0.png)

How can we install the extension for magento 2.4.3 ?

**Comment by tjwiebell** [comment]
Closing as duplicate of #37. Please see comments section for immediate patch and estimated timeline to publish fix.
